### ISSUE TITLE
Issue during jfphone rebuild

### ISSUE THREAD

**Issue by ftasso** [pquiring/javaforce#14]
Hello,
I'm trying to rebuild the jfphone using the last release 54.1 but something doesn't work.
After a successful call I have that:

[2024/04/23 20:03:56] java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "javaforce.voip.SDP$Stream.getIP()" is null
	at javaforce.voip.RTP.findChannel(RTP.java:385)
	at javaforce.voip.RTP$Worker.run(RTP.java:437)

[2024/04/23 20:03:56] RTPChannel.writeRTP() : not active
[2024/04/23 20:03:56] RTPChannel.writeRTP() : not active
[2024/04/23 20:03:56] RTPChannel.writeRTP() : not active
[2024/04/23 20:03:56] RTPChannel.writeRTP() : not active

Could you make a check?

Thank you so much,
Fabrizio

**Comment by pquiring** [comment]
Out of town right now returning Friday.  I'll test then.

**Comment by pquiring** [comment]
I'm not getting that exception but I can confirm audio is not working.  I'll debug that today.
Thanks,

**Comment by pquiring** [comment]
Fixed with 807bec3302d3e4103dd5c98b949638f06b972f24

**Comment by pquiring** [comment]
jfPhone/1.28 released should fix your issues.

Thanks,

**Comment by ftasso** [comment]
Hello Peter,
yes, it works!
Please make the javaforce.jar available in maven repository.

Thank you,
Fabrizio

**Comment by pquiring** [comment]
Will do.
