### ISSUE TITLE
Compatibility issue between jfphone and JavaForce 68.0

### ISSUE THREAD

**Issue by ftasso** [pquiring/javaforce#16]
Hello,
I am experiencing a compatibility issue between jfphone and the latest version of JavaForce 68.0 downloaded from Maven.

To clarify, I downloaded the latest source code of jfphone from GitHub, but it only works with JavaForce build 56.1. More specifically, I used the javaforce.jar file directly from the standard installation package available for Windows.

When using version 68.0 from Maven (and even with the 68.3 sources), I encounter problems retrieving the RTP port from the Asterisk server: "m=audio 0 UDP/RTP/AVP 9 96".

I am attaching SIP sequences created with both jfphone/JavaForce_56.1 and jfphone/JavaForce_68.0 on Asterisk 18.20.2 (I also tested with Asterisk 16 and 20) along with a portion of the log:

[jfphone-sip-protocol-line1-56-1.log](https://github.com/user-attachments/files/17174908/jfphone-sip-protocol-line1-56-1.log)
[jfphone-sip-protocol-line1-68-0.log](https://github.com/user-attachments/files/17174891/jfphone-sip-protocol-line1-68-0.log)

[2024/09/28 15:35:47] RTP:No channel found:192.168.0.201:17050
[2024/09/28 15:35:47] Audio:writeRTP
[2024/09/28 15:35:47] RTPChannel.writeRTP:192.168.0.201:0
[2024/09/28 15:35:47] java.net.SocketException: Can't send to port 0
        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:888)
        at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:952)
        at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:193)
        at java.base/java.net.DatagramSocket.send(DatagramSocket.java:662)
        at javaforce.voip.TransportUDP.send(TransportUDP.java:46)
        at javaforce.voip.RTPChannel.writeRTP(RTPChannel.java:106)
        at org.adr.statiallerta.gui.eventmanager.javaforce.base.Audio.process(Audio.java:518)
        at org.adr.statiallerta.gui.eventmanager.javaforce.base.Audio$1.run(Audio.java:78)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)

I hope this information helps.

Thank you in advance for your support!

**Comment by pquiring** [comment]
Fixed with commit : https://github.com/pquiring/javaforce/commit/75a0526e07eb380a8f97196486bbab4da6d8fa97

**Comment by pquiring** [comment]
The next major release should be early next week.

**Comment by ftasso** [comment]
Hello,
I will apply the fix and have a check on monday morning.
Thank you so much for your collaboration,have a nice week end

**Comment by pquiring** [comment]
Fixed with JF/69.0 : jfPhone/1.29 : Released on sourceforge.net
